name: FiannaLykoi
favicon: null
layout_spectrum: 0.7115957250352949
typography_spectrum: 0.20896886242553592
title: Fianna Lykoi Cattery
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#514342'
    - '#b2a8a9'
    - '#040000'
    - '#a87770'
    - '#fef9f0'
  brandStrength: 0.41224984964355826
  lightness: 0.04229087941348553
  saturation: 0.7358550869394094
  rhythmicContrast: 0.013252709060907364
purpose: []
